force-app/main/default/objects/Lote_de_Caf__c/Lote_de_Caf__c.object-meta.xml
<CustomObject>
    <label>Lote de Café</label>
    <nameField>
        <displayFormat>LOTE-{0000}</displayFormat>
        <label>Código do Lote</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lotes de Café</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Lote_de_Caf__c/fields/Acidez__c.field-meta.xml
<CustomField>
    <fullName>Acidez__c</fullName>
    <label>Acidez</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lote_de_Caf__c/fields/Corpo__c.field-meta.xml
<CustomField>
    <fullName>Corpo__c</fullName>
    <label>Corpo</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lote_de_Caf__c/fields/Docura__c.field-meta.xml
<CustomField>
    <fullName>Docura__c</fullName>
    <label>Doçura</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lote_de_Caf__c/fields/Nota_SCA__c.field-meta.xml
<CustomField>
    <fullName>Nota_SCA__c</fullName>
    <label>Nota SCA</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LoteCafeTriggerHandler.cls
public with sharing class LoteCafeTriggerHandler {
    public static void calcularPontuacao(List<Lote_de_Caf__c> novosLotes){
        for(Lote_de_cof_c lote : novosLotes) {
            Decimal corpo = lote.Corpo__c != null ? lote.Corpo__c : 0;
            Decimal acidez = lote.Acidez__c != null ? lote.Acidez__c : 0;
            Decimal docura = lote.Docura__c != null ? lote.Docura__c : 0;

            Decimal mediaSCA = (corpo + acidez + docura) / 3;
            lote.Nota_SCA__c = mediaSCA;

            if(mediaSCA>=80){
                lote.stats__c = 'Pronto para Exportação';

            }
        }
    }
}